name: GFM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==24.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - idna==3.10
      - jinja2==3.1.5
      - joblib==1.4.2
      - littleutils==0.2.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==2.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ogb==1.3.6
      - outdated==0.2.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.2.1
      - psutil==6.1.1
      - pyg-lib==0.4.0+pt25cu124
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.32.3
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - torch==2.5.1
      - torch-cluster==1.6.3+pt25cu124
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu124
      - torch-sparse==0.6.18+pt25cu124
      - torch-spline-conv==1.2.2+pt25cu124
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - yarl==1.18.3

